// Sitenin ilk hâli. Deniz düzenleme modunda kaydettiğinde bunun yerine
// Blob'daki ozel/icerik.json kullanılır; yeni eklenen alanlar buradan tamamlanır.
export const DEFAULT_CONTENT = {
  version: 2,
  names: { me: 'Deniz', you: 'Sena' },
  site: {
    title: 'Sena’ya ❤',
    since: '2024-02-14T20:00',
    sinceSet: false,
    birthday: '',
    whatsapp: '',
    events: true,
    music: { src: '', title: 'Bizim Şarkımız', artist: '' },
    chapters: {
      home: true, story: true, gallery: true, letter: true, reasons: true,
      quiz: true, dreams: true, surprise: true, finale: true,
    },
    lock: {
      enabled: false,
      question: 'Bana en çok ne diye seslenirsin?',
      hint: 'Sadece ikimizin bildiği bir kelime 🤫',
      wrong: 'Hımm… bu değil gibi 🙈 Bir daha dene!',
    },
  },
  // Buradaki hiçbir şey ziyaretçiye gönderilmez
  secret: {
    lockAnswers: [],
    // Sena bir şey yapınca Deniz'in telefonuna haber: WhatsApp (CallMeBot) ve/veya ntfy
    notify: { waPhone: '', waKey: '', ntfyTopic: '' },
  },

  intro: {
    kicker: 'Sadece senin için hazırlandı',
    to: 'Sena’ya',
    from: 'Deniz’den, sevgiyle',
    letter: 'Seni seviyorum',
    hint: 'Açmak için mühre dokun',
  },

  home: {
    title: 'Sen & Ben',
    desc: 'Her şeyin başladığı yer',
    kicker: 'Bir varmış, bir yokmuş…',
    heroTitle: 'Deniz & Sena',
    lead: '…bir gün iki kalp birbirini buldu. O günden beri dünya, eskisinden çok daha güzel bir yer.',
    rotatingPrefix: 'Sen benim',
    rotating: [
      'en güzel tesadüfüm',
      'huzurum',
      'gülüşümün sebebi',
      'evim',
      'en sevdiğim yerim',
      'bir tanemsin',
      'her şeyim',
    ],
    photo: '',
    photoCaption: 'En sevdiğim fotoğrafımız',
    counterTitle: 'Birlikte geçirdiğimiz zaman',
    counterNote: '…ve her saniyesi ömrüme bedel.',
    statsTitle: 'Sayılarla biz',
    dailyTitle: 'Bugünün notu',
    daily: [
      'Bugün de dünyanın en şanslı insanıyım, çünkü sen varsın.',
      'Aklıma her düştüğünde yüzümde kocaman bir gülümseme beliriyor. Bugün de öyle oldu, hem de defalarca.',
      'Seninle geçen sıradan bir gün, başkasıyla geçen bir bayramdan daha güzel.',
      'Bugün kendine iyi bak; çünkü sen benim en değerli hazinemsin.',
      'Kalbimin en güzel köşesinde senin adın yazıyor.',
      'Bir kahve, bir sohbet, bir de sen… Mutluluk bu kadar basit.',
      'Bugün gülümse; o gülüş benim dünyamı aydınlatıyor.',
      'Seni düşünmek, günün en sevdiğim anı.',
      'Uzakta olsan bile kalbim hep yanında.',
      'Seninle her şey daha anlamlı: şarkılar, sokaklar, hatta yağmur bile.',
      'Bugün de seni dünkünden biraz daha çok seviyorum.',
      'Sen yanımdayken zaman sanki biraz daha yavaş akıyor.',
      'Hayatıma kattığın renkler için sana teşekkür ederim.',
      'Gözlerine her baktığımda sana yeniden âşık oluyorum.',
      'Yorulduğunda aklına getir: seni çok seven biri var.',
      'Sen benim en güzel alışkanlığımsın.',
      'Bugün sana sarılmayı çok istiyorum. Bu notu sanal bir sarılma say 🤗',
      'Seninle yaşlanmak, hayallerimin en güzeli.',
      'Dünyanın bütün güzel kelimeleri seni anlatmaya yetmez.',
      'İyi ki o gün yollarımız kesişti.',
      'Sen benim huzurumsun; bunu hiç unutma.',
      'Bugün kendini sevilmiş hisset — çünkü öylesin, hem de çok.',
      'Bir gün değil, her gün yine seni seçerdim.',
      'Gülüşün, en sevdiğim manzara.',
      'Hayallerimin hepsinde sen varsın.',
      'Ne olursa olsun, ben hep senin tarafındayım.',
      'Kalbimin anahtarı sende; sakın kaybetme 🔑',
      'Seninle susmak bile güzel.',
      'Bugün de benim gözümde dünyanın en güzel insanısın.',
      'Seni seviyorum. Dün de sevdim, yarın da seveceğim.',
    ],
    quote: 'Seni sevmek, bugüne kadar yaptığım en kolay ve en güzel şey.',
    secretHint: 'Psst… isimlerimize üç kez dokun 🤫',
    secretNote: 'Buldun! 🙈 Bu sitenin her köşesinde sen varsın, ama bu not sadece seni bulsun diye burada saklıydı: Seni dünden çok, yarından az seviyorum. Ve bunu her gün, her fırsatta sana yeniden söylemek istiyorum.',
    cta: 'Hikâyemize başla',
  },

  story: {
    title: 'Hikâyemiz',
    desc: 'Birlikte yazdığımız sayfalar',
    intro: 'Her aşk hikâyesi güzeldir; ama bizimki, benim en sevdiğim.',
    items: [
      {
        date: 'Tanıştığımız gün',
        title: 'İlk Karşılaşma',
        text: 'O gün her şey sıradan başladı. Sonra sen geldin ve hiçbir şey eskisi gibi olmadı. Gözlerin, kalbimin kapısını çalan ilk misafirdi.',
        photo: '',
      },
      {
        date: 'İlk buluşma',
        title: 'İlk Buluşmamız',
        text: 'Heyecandan ne konuştuğumu hatırlamıyorum ama gülüşünü hiç unutmadım. Saatler dakika gibi geçti; o gün zaman bile bizi kıskandı.',
        photo: '',
      },
      {
        date: 'O özel an',
        title: 'İlk “Seni Seviyorum”',
        text: 'Kalbimde çoktan yazılıydı, sadece dudaklarımın cesaret etmesi gerekiyordu. O iki kelimeyi söylediğim an, dünyanın en şanslı insanı oldum.',
        photo: '',
      },
      {
        date: 'Unutulmaz bir gün',
        title: 'Birlikte İlk Yolculuğumuz',
        text: 'Yol ne kadar uzun olursa olsun, yanımda sen varken her yer ev gibiydi. Bavullarımıza anılar, kahkahalar ve bolca fotoğraf sığdırdık.',
        photo: '',
      },
      {
        date: 'Bugün',
        title: 'Ve Hâlâ…',
        text: 'Hâlâ ilk günkü heyecanla, hatta daha fazlasıyla seviyorum seni. Hikâyemizin en güzel sayfaları ise henüz yazılmadı.',
        photo: '',
      },
    ],
    outro: 'Ve devamını birlikte yazacağız…',
  },

  gallery: {
    title: 'Anılarımız',
    desc: 'Kalbimde asılı kareler',
    intro: 'Her fotoğraf, kalbimde asılı duran küçük bir pencere. Birine dokun, o güne birlikte dönelim.',
    slideshow: 'Slayt gösterisini başlat',
    items: [
      { photo: '', caption: 'Bu gülüşe bayılıyorum' },
      { photo: '', caption: 'En sevdiğim günlerden biri' },
      { photo: '', caption: 'Sen + Ben = ❤' },
      { photo: '', caption: 'Zamanı durdurabilseydim…' },
      { photo: '', caption: 'Yine sen, yine o gülüş' },
      { photo: '', caption: 'Seninle her yer güzel' },
    ],
  },

  letter: {
    title: 'Sana Mektubum',
    desc: 'Kalbimden sana birkaç satır',
    intro: 'Bazı şeyler yazıya dökülünce daha çok anlam kazanıyor…',
    greeting: 'Sevgili Sena’m,',
    body: 'Bu satırları yazarken yüzümde kocaman bir gülümseme var, çünkü seni düşünmek bile içimi ısıtmaya yetiyor. Sana olan sevgimi anlatmaya kelimelerin yetmeyeceğini biliyorum; yine de denemek istedim. Çünkü sen, uğruna kelimelerin bile yarıştığı birisin.\n\nHayatıma girdiğin günden beri her şey daha renkli. Sabahlar daha aydınlık, şarkılar daha anlamlı, sıradan günler bile bayram gibi. Bir mesajın, bir bakışın, bir gülüşün bütün yorgunluğumu alıp götürüyor. Yanında kendim olabiliyorum ve bu, dünyadaki en huzurlu his.\n\nBirlikte güldüğümüz anları, gece yarısı sohbetlerimizi, en saçma şeylere bile kahkahalarla güldüğümüz o anları o kadar çok seviyorum ki… Zor zamanlarımda elimi bırakmadığın, en kötü günümde bile bana iyi geldiğin için sana ne kadar teşekkür etsem az.\n\nBiliyorum; bazen dağınık, bazen inatçı, bazen de fazla sessiz olabiliyorum. Ama şunu hiç unutma: kalbim her zaman seninle. Ne olursa olsun yanında olmak, seni mutlu etmek ve seninle yaşlanmak istiyorum. Saçlarımız ağarsa da bu heyecan hiç eksilmesin istiyorum.\n\nSen benim en güzel tesadüfüm, en doğru kararım, en sevdiğim yerimsin. İyi ki doğdun, iyi ki karşıma çıktın, iyi ki benimlesin. Seni dünden çok, yarından az seviyorum; çünkü yarın seni bugünden de çok seveceğim.',
    closing: 'Seni her şeyden çok seven,',
    signature: 'Deniz',
    openWhenTitle: 'Zamanı gelince aç',
    openWhenIntro: 'Bir de bunlar var: her biri doğru anı bekleyen küçük mektuplar. İhtiyacın olduğunda birini aç; ben oradayım 💌',
    openWhen: [
      {
        icon: '🥺',
        label: 'Beni özlediğinde aç',
        text: 'Ben de seni özledim. Hem de şu an, bu satırları okuduğun şu saniyede bile. Gözlerini kapat ve en son sarıldığımız anı düşün… İşte ben tam oradayım. Aramızdaki mesafe ne kadar olursa olsun, kalbim hep seninle. Şimdi bana bir mesaj at; inan bana, ben de tam o anda seni düşünüyor olacağım.',
      },
      {
        icon: '🌧️',
        label: 'Canın sıkıldığında aç',
        text: 'Hey, güzel kalpli… Bazı günler böyle olur; gökyüzü kararır, her şey üst üste gelir. Ama unutma: bulutlar ne kadar kalın olursa olsun, güneş hep oradadır. Sen o güneşsin. Derin bir nefes al, sevdiğin bir şarkıyı aç ve bil ki seni çok seven biri, senin gülüşün için her şeyi yapmaya hazır. Beni ara; bu günü beraber geçirelim.',
      },
      {
        icon: '🌙',
        label: 'Uyuyamadığında aç',
        text: 'Uykun mu kaçtı? Gel, sana bir masal anlatayım: Bir zamanlar dünyanın en güzel gözlerine sahip biri varmış. O gözlere bakan biri, o günden sonra kendini hiç yalnız hissetmemiş… Şimdi gözlerini kapat. Yanında olduğumu, saçlarını okşadığımı düşün. Yarın yine birbirimize kavuşacağız. İyi geceler, bir tanem.',
      },
      {
        icon: '🤍',
        label: 'Kendini yalnız hissettiğinde aç',
        text: 'Yalnız değilsin. Hiçbir zaman olmadın, olmayacaksın da. Ben her zaman buradayım; bir mesaj, bir telefon kadar yakınındayım. Sen benim en sevdiğim insansın ve bu hiç değişmeyecek. Şimdi aynaya bak ve kendine gülümse; çünkü ben o yüzü dünyadaki her şeyden çok seviyorum.',
      },
      {
        icon: '☀️',
        label: 'Çok mutlu olduğunda aç',
        text: 'Mutlu olduğunu bilmek beni de dünyanın en mutlu insanı yapıyor! Bu anın tadını çıkar, sonra gel bana her şeyi anlat; senin sevincin benim de sevincim. O gülüş hep yüzünde olsun istiyorum. Seninle kutlamak için sabırsızlanıyorum 🎉',
      },
      {
        icon: '😤',
        label: 'Bana kızdığında aç',
        text: 'Tamam, haklısın. (Muhtemelen haklısın 😄) Bazen dağınık, bazen inatçı olabiliyorum; biliyorum. Ama şunu da bil: seni kırmak istemem, asla. Kızgınlığın geçince gel konuşalım; ben yine sana sarılmak için bekliyor olacağım. Seni kızgınken bile çok seviyorum.',
      },
    ],
  },

  reasons: {
    title: 'Neden Sen?',
    desc: 'Seni sevmemin küçük sebepleri',
    intro: 'Seni sevmek için aslında hiçbir sebebe ihtiyacım yok… ama yine de birkaçını yazdım. Kartlara dokun!',
    randomLabel: 'Rastgele bir sebep göster',
    items: [
      'Gülüşün, en kötü günümü bile güzelleştiriyor.',
      'Yanında hiç rol yapmadan, olduğum gibi olabiliyorum.',
      'Gözlerinin içi güldüğünde dünyam duruyor.',
      'Beni bazen benden bile iyi tanıyorsun.',
      'En saçma şakalarıma bile gülüyorsun.',
      'Sarılman, dünyadaki en güvenli yer.',
      'Hayallerimi dinliyor, onlara ortak oluyorsun.',
      'Zor anlarımda elimi hiç bırakmıyorsun.',
      'Sesini duymak her şeye iyi geliyor.',
      'Seninle sessizlik bile güzel.',
      'Her gün beni biraz daha iyi biri yapıyorsun.',
      'Çünkü sen, sensin. Başka bir sebebe gerek yok.',
    ],
    meterTitle: 'Seni ne kadar seviyorum?',
    meterHint: 'Ölçmek için kalbe dokun',
    meterResult: 'Ölçülemeyecek kadar çok!',
    meterNote: 'Hata: Sevgi miktarı cihazın kapasitesini aştı 😅',
  },

  quiz: {
    title: 'Beni Ne Kadar Tanıyorsun?',
    desc: 'Küçük, tatlı bir sınav',
    intro: 'Bakalım beni ne kadar tanıyorsun? Yanlış cevap yok… aslında var ama seni yine de seviyorum 😄',
    start: 'Sınava başla',
    questions: [
      {
        q: 'Deniz’in dünyada en sevdiği şey ne?',
        options: ['Uyumak', 'Yemek', 'Sena 💖', 'Telefonu'],
        answer: 2,
        note: 'Tabii ki sen! Başka bir cevabı yoktu zaten 😌',
      },
      {
        q: 'Deniz’in gününü en çok ne güzelleştirir?',
        options: ['Güzel bir kahve', 'Güneşli bir hava', 'Sena’nın gülüşü', 'Hafta sonu olması'],
        answer: 2,
        note: 'Gülüşün benim güneşim ☀️',
      },
      {
        q: 'Deniz seni en çok ne zaman özler?',
        options: ['Sabah uyanınca', 'Gece uyumadan önce', 'Gün içinde bir ara', 'Her an 🥺'],
        answer: 3,
        note: 'Her an, her saniye… Hatta şu an bile!',
      },
      {
        q: 'Deniz’in telefonunda en çok kimin fotoğrafı var?',
        options: ['Manzaraların', 'Yemeklerin', 'Sena’nın', 'Ekran görüntülerinin'],
        answer: 2,
        note: 'Galerim resmen senin sergin 📸',
      },
      {
        q: 'Deniz’in en büyük hayali ne?',
        options: ['Dünyayı gezmek', 'Zengin olmak', 'Sena’yla bir ömür', 'Hepsi ama en çok üçüncüsü'],
        answer: 3,
        note: 'Dünyayı da gezeceğiz ama yanımda sen olacaksın 🌍',
      },
      {
        q: 'Deniz seni ne kadar seviyor?',
        options: ['Çok', 'Çok çok', 'Anlatılamayacak kadar', 'Sonsuz kere sonsuz'],
        answer: 3,
        note: 'Aslında bu da az kaldı ama daha büyük bir sayı bulamadım ♾️',
      },
    ],
    resultPerfect: 'Tam puan! Beni benden iyi tanıyorsun 😍',
    resultGood: 'Neredeyse mükemmel! Zaten kalbim tamamen senin 💕',
    resultLow: 'Olsun, beni tanımak için önümüzde koca bir ömür var 😘',
    retry: 'Tekrar çöz',
  },

  dreams: {
    title: 'Hayallerimiz',
    desc: 'Birlikte yapacaklarımız',
    intro: 'Seninle yapmak istediğim o kadar çok şey var ki… İşte listemizden birkaçı. Tik atılanlar, gerçekleşenler!',
    items: [
      { text: 'Birlikte gün doğumunu izlemek', done: true },
      { text: 'Kapadokya’da balonla gökyüzüne yükselmek', done: false },
      { text: 'Deniz kenarında uzun bir kahvaltı', done: false },
      { text: 'Yurt dışında birlikte bir tatil', done: false },
      { text: 'Beraber yemek yapmayı öğrenmek (ve mutfağı yakmamak 😄)', done: false },
      { text: 'Karlı bir dağ evinde yılbaşı', done: false },
      { text: 'Bir yıldız kayarken aynı dileği tutmak', done: false },
      { text: 'Kendi evimizi kurmak', done: false },
      { text: 'Yaşlanınca aynı bankta oturup gün batımını izlemek', done: false },
    ],
    suggestTitle: 'Senin de bir hayalin var mı?',
    suggestPlaceholder: 'Hayalini yaz…',
    suggestButton: 'Listemize ekle 💭',
    suggestThanks: 'Hayalin bana ulaştı! Listemize ekleyeceğim ✨',
  },

  surprise: {
    title: 'Sürprizler',
    desc: 'Senin için küçük hediyeler',
    intro: 'Sana birkaç küçük hediyem var. Biri saklı; diğerleri istediğin zaman kullanabileceğin aşk kuponları!',
    scratchTitle: 'Kazı Kazan',
    scratchHint: 'Parmağınla kazı, sürprizini gör!',
    scratchPrize: 'Tebrikler! 🎉 Sınırsız sarılma ve bir ömür boyu öpücük kazandın. Ödülünü benden istediğin zaman alabilirsin 💋',
    couponsTitle: 'Aşk Kuponları',
    couponsIntro: 'Kullanmak istediğin kupona dokun, bana haber gelsin 😉',
    coupons: [
      { icon: '🤗', title: 'Sınırsız Sarılma', text: 'Geçerlilik süresi: sonsuza dek' },
      { icon: '🎬', title: 'Film Gecesi', text: 'Film seçimi tamamen senden, itiraz yok!' },
      { icon: '☕', title: 'Kahvaltı Benden', text: 'Yatağa servis dahil' },
      { icon: '🍕', title: 'Canın Ne Çekerse', text: 'İstediğin yemek, anında sipariş' },
      { icon: '💆', title: 'Masaj Kuponu', text: '15 dakika, pazarlıksız' },
      { icon: '🏆', title: 'Tartışma Kazanma Hakkı', text: 'Haklı olmasan bile 😄' },
    ],
  },

  finale: {
    title: 'Sonsuza Dek',
    desc: 'Sana sormak istediğim bir şey var',
    pre: 'Ve şimdi… sana sormak istediğim bir şey var.',
    question: 'Benimle sonsuza dek kalır mısın?',
    yes: 'Evet',
    no: 'Hayır',
    noTexts: [
      'Emin misin? 🥺',
      'Bir daha düşün!',
      'Yanlış butona basıyorsun',
      'Bu buton bozuk galiba 😅',
      'Kaçamazsın 😄',
      'Evet’e bas artık!',
      'Olmaz öyle şey!',
      'Kalbimi kırma 💔',
    ],
    noGone: 'Görünüşe göre tek bir seçeneğin var 😄',
    successTitle: 'Biliyordum!',
    big: 'Seni Seviyorum',
    successText: 'Sen benim bugünüm, yarınım ve sonsuzumsun. İyi ki varsın, iyi ki benimlesin.',
    photo: '',
    replyTitle: 'Bana küçük bir not bırakır mısın?',
    replyPlaceholder: 'Kalbinden geçenleri yaz…',
    replyButton: 'Gönder 💌',
    replyThanks: 'Notun bana ulaştı. Seni seviyorum 💖',
    restart: 'Baştan izle',
  },

  footer: 'Sonsuza dek seninle ❤',
};
